apiVersion: v1
kind: Service
metadata:
  name: map-svc
  labels:
    app: map
spec:
  selector:
    app: map
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      # nodePort: 30001
